version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01    
    working_directory: ~/teamhub
    steps:
      - checkout
      - run:
          name: Start container and run docker-compose
          command: |
            mv ./backend/data/config.template.json ./backend/data/config.json
            docker build ./docker -t teamhub
            docker-compose up -d
      - run:
          name: Install packages
          command: docker exec teamhub_nodejs npm install
      - run:
          name: Run Tests
          command: docker exec teamhub_nodejs npm run test

  deploy:
    steps:
      - attach_workspace:
          at: ~/tmp/circlci-now
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: |
            now --token $ZEIT_TOKEN --local-config .now/now.production.json
            now --token $ZEIT_TOKEN --local-config .now/now.production.json alias

